// MARK: - WARNING: GENERATED CODE
// GENERATED BY: SwiftPublicPackageStringsGenerator
// ---------------------------------------------------------------------------
// This file is auto-generated. Do not modify this file directly.
// Any changes made here will be lost when the generation process runs again.
// ---------------------------------------------------------------------------

import Foundation

public extension LocalizedStringResource {

__CODE__    

}